async function request(method, path, body) {
  const res = await fetch(`/api${path}`, {
    method,
    headers: { 'Content-Type': 'application/json' },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  if (res.status === 204) return null;
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || `Request failed (${res.status})`);
  return data;
}

export const api = {
  getOptions: () => request('GET', '/characters/options'),
  listCharacters: () => request('GET', '/characters'),
  getCharacter: (id) => request('GET', `/characters/${id}`),
  createCharacter: (payload) => request('POST', '/characters', payload),
  deleteCharacter: (id) => request('DELETE', `/characters/${id}`),
  getWorld: () => request('GET', '/world'),
  getMap: (characterId) => request('GET', `/world/map${characterId ? `?characterId=${characterId}` : ''}`),
  getContinent: (idOrName) => request('GET', `/continents/${encodeURIComponent(idOrName)}`),
  visitLocation: (id, characterId) => request('POST', `/world/locations/${id}/visit`, { characterId }),
  getLocation: (id) => request('GET', `/world/locations/${id}`),
  getItems: (characterId) => request('GET', `/world/characters/${characterId}/items`),
  listMonsters: () => request('GET', '/world/monsters'),
  startBattle: (payload) => request('POST', '/battles', payload),
  getBattle: (id) => request('GET', `/battles/${id}`),
  preview: (id, abilityId, targetKey) =>
    request('GET', `/battles/${id}/preview?abilityId=${abilityId}&targetKey=${targetKey}`),
  battleAction: (id, action) => request('POST', `/battles/${id}/action`, action),
  getParty: (leaderId) => request('GET', `/party/${leaderId}`),
  getSources: (leaderId) => request('GET', `/party/${leaderId}/sources`),
  getRecruits: (leaderId, source) => request('GET', `/party/${leaderId}/recruits${source ? `?source=${source}` : ''}`),
  recruit: (leaderId, payload) => request('POST', `/party/${leaderId}/recruit`, payload),
  adjustRelation: (memberId, payload) => request('POST', `/party/member/${memberId}/relation`, payload),
  sweepParty: (leaderId) => request('POST', `/party/${leaderId}/sweep`),
  setMemberStatus: (memberId, status) => request('POST', `/party/member/${memberId}/status`, { status }),
  getUpgrades: (leaderId) => request('GET', `/upgrades/${leaderId}`),
  getPartyPoints: (leaderId) => request('GET', `/upgrades/${leaderId}/points`),
  spendUpgrade: (leaderId, node) => request('POST', `/upgrades/${leaderId}/spend`, { node }),
  dialogueOptions: () => request('GET', '/dialogue/options'),
  dialogueStatus: () => request('GET', '/dialogue/status'),
  npcsAtLocation: (locationId) => request('GET', `/dialogue/npc/${locationId}`),
  getConversation: (leaderId, kind, refId) => request('GET', `/dialogue/${leaderId}/${kind}/${refId}`),
  say: (leaderId, kind, refId, text) => request('POST', `/dialogue/${leaderId}/${kind}/${refId}`, { text }),
  startTravel: (payload) => request('POST', '/travel', payload),
  getTravel: (id) => request('GET', `/travel/${id}`),
  chooseTravel: (id, choice) => request('POST', `/travel/${id}/choose`, { choice }),
  getRitual: (leaderId) => request('GET', `/resurrections/${leaderId}`),
  startResurrection: (leaderId, memberId) => request('POST', `/resurrections/${leaderId}/start`, { memberId }),
  listSaves: (characterId) => request('GET', `/saves/${characterId}`),
  listAllSaves: () => request('GET', '/saves/all'),
  createSave: (characterId, name) => request('POST', `/saves/${characterId}`, { name }),
  loadSave: (saveId) => request('POST', `/saves/slot/${saveId}/load`),
  deleteSave: (saveId) => request('DELETE', `/saves/slot/${saveId}`),
  exportSave: (saveId) => request('GET', `/saves/slot/${saveId}/export`),
  getInventory: (characterId) => request('GET', `/items/${characterId}`),
  equipItem: (characterId, key) => request('POST', `/items/${characterId}/equip`, { key }),
  unequipItem: (characterId, slot) => request('POST', `/items/${characterId}/unequip`, { slot }),
  useItem: (characterId, key) => request('POST', `/items/${characterId}/use`, { key }),
  removeBuff: (characterId, payload) => request('DELETE', `/items/${characterId}/buffs`, payload),
  tickBuffs: (characterId, turns = 1) => request('POST', `/items/${characterId}/buffs/tick`, { turns }),
  listLore: () => request('GET', '/lore'),
  getLore: (key) => request('GET', `/lore/${key}`),
};
